### ISSUE TITLE
Add RSA crypto

### ISSUE THREAD

**Issue by hoanghiephui** [TGIO/RNCryptorNative#10]
You can build more features RSA encryption?

**Comment by rnapier** [comment]
I can't speak for @TGIO, but that would be a very surprising feature to add to this library. This library implements a specific encryption format (RNCryptor). It is not a general-purpose cryptography library.

**Comment by hoanghiephui** [comment]
I understand, but I found this library that uses cryptopp (RSA is one of the features that it supports)

**Comment by rnapier** [comment]
I don't understand what RSA would be used for in this library. RNCryptor is a specific cross-platform data format that requires specific algorithms, data ordering, and metadata. It is not a generic toolbox of crypto primitives. Toolboxes like cryptopp give you a wide variety of tools you can use to build custom data formats, and leave it to you to know how to do that correctly (it is very easy to use these primitives insecurely and most people do). RNCryptor is a existing format that assembles specific primitives in a secure way that is portable across platforms.

What problem are you trying to solve?

**Comment by getsadzeg** [comment]
@rnapier can't agree more.

Closing this
