### ISSUE TITLE
the method encrypt in RNCryptorNative and encryptData in JNCryptor

### ISSUE THREAD

**Issue by cs8** [TGIO/RNCryptorNative#11]
rncryptor.encrypt(text ,password) 
but AES256JNCryptor is 
jncryptor.encryptData(text.getbytes(),password.toCharArray()) 
the result are not the same , And how to match it？

**Comment by rnapier** [comment]
No two encryptions should ever match in the RNCryptor format. That is by design. The format includes random salts to avoid several kinds of attack. Any implementation should still decrypt correctly
