### ISSUE TITLE
about minSdkVersion

### ISSUE THREAD

**Issue by hwangjr** [TGIO/RNCryptorNative#9]
I found the `minSdkVersion` is `16`, if i set to `15`, is it still work ok?

otherwise, i found the gradle dependency config is:

```
dependencies {
    compile 'com.github.tgio:rncryptor-native:0.0.8'
}
```

Maybe you should specify the `aar` format : 

```
dependencies {
    compile 'com.github.tgio:rncryptor-native:0.0.8@aar'
}
```

**Comment by getsadzeg** [comment]
`minSdkVersion` means min SDK version. So, it shouldn't work. You could try it instead of submitting issue.

**Comment by getsadzeg** [comment]
@TGIO closing this.
